POST http://localhost:8069/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "object",
    "method": "execute_kw",
    "args": [
      "infra",
      "2",
      "admin",
      "res.partner",
      "search_read",
      [
        [
          [
            "id",
            ">",
            "30"
          ]
        ],
        [
          "name"
        ]
      ]
    ]
  }
}

###

POST http://localhost:8069/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "common",
    "method": "authenticate",
    "args": [
      "infra",
      "admin",
      "admin",
      ""
    ]
  }
}

###

POST https://demo.odoo.com/start
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "common",
    "method": "start"
  }
}

###

POST https://demo3.odoo.com/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "object",
    "method": "execute_kw",
    "args": [
      "demo_150_1640806878",
      "2",
      "admin",
      "res.partner",
      "search_read",
      [
        [
          [
            "id",
            ">",
            2
          ]
        ],
        [
          "name"
        ]
      ]
    ]
  }
}

###

POST https://demo3.odoo.com/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "object",
    "method": "execute_kw",
    "args": [
      "demo_150_1641038508",
      "2",
      "admin",
      "res.partner",
      "search_read",
      [
        [
          [
            "id",
            ">",
            2
          ]
        ]
      ],
      {
        "fields": [
          "name"
        ],
        "limit": 5
      }
    ]
  }
}

###

POST https://demo3.odoo.com/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "object",
    "method": "execute_kw",
    "args": [
      "demo_150_1641038508",
      "2",
      "admin",
      "res.partner",
      "create",
      [
        {
          "name": "t"
        }
      ]
    ]
  }
}

###

POST https://demo3.odoo.com/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "object",
    "method": "execute_kw",
    "args": [
      "demo_150_1641038508",
      "2",
      "admin",
      "res.partner",
      "write",
      [
        [
          61
        ],
        {
          "name": "t"
        }
      ]
    ]
  }
}


###

POST https://demo3.odoo.com/jsonrpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "call",
  "id": 42,
  "params": {
    "service": "object",
    "method": "execute_kw",
    "args": [
      "demo_150_1641038508",
      "2",
      "admin",
      "res.partner",
      "unlink",
      [
        61
      ]
    ]
  }
}
